CREATE TABLE reminder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(4096),
    remind TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_reminder_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);